apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-south-1

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    maxSize: 10
    availabilityZones: ["ap-south-1a"]
    ssh:
      publicKeyName: eks-keypair
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]
    # enableTypes: [*]